"""Added required tables

Revision ID: 294667587568
Revises: 3571b7a89ce3
Create Date: 2022-12-22 18:21:18.540694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294667587568'
down_revision = '3571b7a89ce3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
