"""Added required tables

Revision ID: 3571b7a89ce3
Revises: 
Create Date: 2022-12-22 18:19:23.497342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3571b7a89ce3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('car_id')
    )
    op.create_index(op.f('ix_cars_car_id'), 'cars', ['car_id'], unique=False)
    op.create_table('rate',
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('rate_name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('rate_id')
    )
    op.create_index(op.f('ix_rate_rate_id'), 'rate', ['rate_id'], unique=False)
    op.create_table('rates',
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.car_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rate_id'], ['rate.rate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rate_id', 'car_id')
    )
    op.create_index(op.f('ix_rates_car_id'), 'rates', ['car_id'], unique=False)
    op.create_index(op.f('ix_rates_rate_id'), 'rates', ['rate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rates_rate_id'), table_name='rates')
    op.drop_index(op.f('ix_rates_car_id'), table_name='rates')
    op.drop_table('rates')
    op.drop_index(op.f('ix_rate_rate_id'), table_name='rate')
    op.drop_table('rate')
    op.drop_index(op.f('ix_cars_car_id'), table_name='cars')
    op.drop_table('cars')
    # ### end Alembic commands ###
